# Generated by Django 6.0.1 on 2026-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sectiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontitle',
            name='highlight',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
