# Generated by Django 6.0.1 on 2026-03-08 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sectiontitle_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='highlight_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='highlight_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='subtitle_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
    ]
