# Generated by Django 6.0.1 on 2026-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcategory_sectiontitle_highlight_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontitle',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='subtitle_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
