# Generated by Django 6.0.1 on 2026-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_sectiontitle_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5),
        ),
    ]
