# Generated by Django 6.0.1 on 2026-03-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcategory_language_alter_project_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_en',
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
