# Generated by Django 6.0.1 on 2026-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_category_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Category'},
        ),
        migrations.AlterModelOptions(
            name='sectiontitle',
            options={'verbose_name': 'Section Title', 'verbose_name_plural': 'Section Title'},
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
    ]
