# Generated by Django 6.0.1 on 2026-03-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='language',
            new_name='default_language',
        ),
        migrations.RenameField(
            model_name='projectcategory',
            old_name='language',
            new_name='default_language',
        ),
        migrations.RenameField(
            model_name='sectiontitle',
            old_name='language',
            new_name='default_language',
        ),
    ]
