# Generated by Django 6.0.1 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_language_project_default_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontitle',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5),
        ),
    ]
