# Generated by Django 6.0.1 on 2026-03-25 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_sectiontitle_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_key',
            field=models.SlugField(blank=True, default='', help_text='Same value for all projects in one area (e.g. jeddah-rawdah). Used for «suggested in same area». Not shown on site.', max_length=120, verbose_name='Area grouping key'),
        ),
        migrations.AddField(
            model_name='project',
            name='area_sqm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bathrooms count'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, default='', help_text='e.g. "Jeddah" / "جدة"', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='project',
            name='city_ar',
            field=models.CharField(blank=True, default='', help_text='e.g. "Jeddah" / "جدة"', max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='project',
            name='city_en',
            field=models.CharField(blank=True, default='', help_text='e.g. "Jeddah" / "جدة"', max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, default='', help_text='e.g. "Al-Rawdah" / "حي الروضة"', max_length=200, verbose_name='District / neighborhood'),
        ),
        migrations.AddField(
            model_name='project',
            name='district_ar',
            field=models.CharField(blank=True, default='', help_text='e.g. "Al-Rawdah" / "حي الروضة"', max_length=200, null=True, verbose_name='District / neighborhood'),
        ),
        migrations.AddField(
            model_name='project',
            name='district_en',
            field=models.CharField(blank=True, default='', help_text='e.g. "Al-Rawdah" / "حي الروضة"', max_length=200, null=True, verbose_name='District / neighborhood'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Has elevator'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_living_hall',
            field=models.BooleanField(default=False, verbose_name='Has living hall (صالة)'),
        ),
        migrations.AddField(
            model_name='project',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Google Maps «Embed» iframe src URL (long paste OK).', verbose_name='Map embed URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='room_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rooms count'),
        ),
        migrations.AddField(
            model_name='project',
            name='sold_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100, for progress ring chart.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sold percentage'),
        ),
        migrations.AddField(
            model_name='project',
            name='structural_warranty_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Structural warranty (years)'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_electrical_extensions',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Electrical extensions warranty'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_electrical_switches',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Electrical switches warranty'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_faucets',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Faucets / mixers warranty'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_lighting',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Lighting warranty'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_plumbing',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Plumbing extensions warranty'),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_water_heaters',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Water heaters warranty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Main cover image'),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project gallery image',
                'verbose_name_plural': 'Project gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
