# Generated by Django 6.0.1 on 2026-03-25 22:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_slug_from_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_sqm_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum unit area, e.g. 96', max_digits=10, null=True, verbose_name='Area to (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='area_sqm_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum unit area, e.g. 79.80', max_digits=10, null=True, verbose_name='Area from (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_private_parking',
            field=models.BooleanField(default=False, verbose_name='Private parking'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area_sqm',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Use area range below for min–max (e.g. 79.80–96).', null=True, verbose_name='Area (m²) — single value'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sold_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0–100 (decimals allowed), for the progress ring.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sold percentage'),
        ),
    ]
