# Generated by Django 6.0.1 on 2026-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_area_range_decimal_sold_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_maid_room',
            field=models.BooleanField(default=False, verbose_name='Maid room'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_smart_home',
            field=models.BooleanField(default=False, verbose_name='Smart home'),
        ),
        migrations.AddField(
            model_name='project',
            name='promo_video',
            field=models.FileField(blank=True, help_text='Optional MP4 or WebM. A “Video” tab appears only when a file is uploaded.', null=True, upload_to='projects/videos/', verbose_name='Promo / walkthrough video'),
        ),
    ]
