# Generated by Django 6.0.1 on 2026-04-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_driver_room_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_badge_text',
            field=models.CharField(blank=True, default='', help_text='Short label on project cards, e.g. «Under construction» / «تم البيع». Leave empty to hide.', max_length=220, verbose_name='Card badge text'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_badge_text_ar',
            field=models.CharField(blank=True, default='', help_text='Short label on project cards, e.g. «Under construction» / «تم البيع». Leave empty to hide.', max_length=220, null=True, verbose_name='Card badge text'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_badge_text_en',
            field=models.CharField(blank=True, default='', help_text='Short label on project cards, e.g. «Under construction» / «تم البيع». Leave empty to hide.', max_length=220, null=True, verbose_name='Card badge text'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_badge_variant',
            field=models.CharField(blank=True, choices=[('', 'Default (brand)'), ('construction', 'Under construction look (amber)'), ('available', 'Promo / available (highlight)'), ('sold', 'Sold (muted)')], default='', help_text='Colors on listing cards. Text is set below (per language).', max_length=20, verbose_name='Card badge style'),
        ),
    ]
