# Generated by Django 6.0.1 on 2026-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_card_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_badge_secondary_text',
            field=models.CharField(blank=True, default='', help_text='Optional. Shown above the main badge on cards & hero, e.g. «1.7 km from Al-Rahhab walkway». Leave empty to hide.', max_length=240, verbose_name='Card badge — secondary line'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_badge_secondary_text_ar',
            field=models.CharField(blank=True, default='', help_text='Optional. Shown above the main badge on cards & hero, e.g. «1.7 km from Al-Rahhab walkway». Leave empty to hide.', max_length=240, null=True, verbose_name='Card badge — secondary line'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_badge_secondary_text_en',
            field=models.CharField(blank=True, default='', help_text='Optional. Shown above the main badge on cards & hero, e.g. «1.7 km from Al-Rahhab walkway». Leave empty to hide.', max_length=240, null=True, verbose_name='Card badge — secondary line'),
        ),
    ]
