# Generated by Django 6.0.1 on 2026-04-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_card_badge_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='card_badge_variant',
            field=models.CharField(blank=True, choices=[('', 'Default (brand)'), ('construction', 'Under construction look (amber)'), ('available', 'Promo / available (highlight)'), ('red', 'Red badge (white text)'), ('sold', 'Sold (check icon, red & white)')], default='', help_text='Look of «Card badge text» on cards and hero. Pick «Red» or «Sold» for red background and white text.', max_length=20, verbose_name='Card badge style'),
        ),
    ]
