# Generated by Django 6.0.1 on 2026-04-13 00:00

from django.db import migrations, models


def backfill_project_status(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().only("id", "card_badge_variant"):
        badge = (project.card_badge_variant or "").strip()
        if badge == "sold":
            project.status = "sold"
        elif badge == "construction":
            project.status = "under_construction"
        else:
            project.status = "current"
        project.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_card_badge_variant_red"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("current", "Current (الحالية)"),
                    ("under_construction", "Under construction (تحت الإنشاء)"),
                    ("sold", "Sold (تم البيع)"),
                ],
                db_index=True,
                default="current",
                help_text="Used for project filters and default status badge style.",
                max_length=24,
                verbose_name="Project status",
            ),
        ),
        migrations.RunPython(backfill_project_status, migrations.RunPython.noop),
    ]
