# Generated by Django 6.0.1 on 2026-04-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_status_badge_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project category', 'verbose_name_plural': 'Project categories'},
        ),
        migrations.AlterModelOptions(
            name='sectiontitle',
            options={'verbose_name': 'Section title', 'verbose_name_plural': 'Section titles'},
        ),
    ]
