# Generated by Django 6.0.1 on 2026-03-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnerbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading_main', models.CharField(blank=True, default='', max_length=120)),
                ('about_heading_main_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('about_heading_main_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('about_heading_span', models.CharField(blank=True, default='', max_length=120)),
                ('about_heading_span_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('about_heading_span_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('about_text', models.TextField(blank=True, default='')),
                ('about_text_ar', models.TextField(blank=True, default='', null=True)),
                ('about_text_en', models.TextField(blank=True, default='', null=True)),
                ('solutions_heading_main', models.CharField(blank=True, default='', max_length=120)),
                ('solutions_heading_main_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('solutions_heading_main_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('solutions_heading_span', models.CharField(blank=True, default='', max_length=120)),
                ('solutions_heading_span_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('solutions_heading_span_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('recent_heading_main', models.CharField(blank=True, default='', max_length=120)),
                ('recent_heading_main_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('recent_heading_main_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('recent_heading_span', models.CharField(blank=True, default='', max_length=120)),
                ('recent_heading_span_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('recent_heading_span_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('contact_heading_main', models.CharField(blank=True, default='', max_length=120)),
                ('contact_heading_main_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('contact_heading_main_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('contact_heading_span', models.CharField(blank=True, default='', max_length=120)),
                ('contact_heading_span_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('contact_heading_span_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('address_ar', models.TextField(blank=True, default='', null=True)),
                ('address_en', models.TextField(blank=True, default='', null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=80)),
                ('phone_ar', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('phone_en', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_ar', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('email_en', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('hours_line1_label', models.CharField(blank=True, default='', max_length=120)),
                ('hours_line1_label_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line1_label_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line1_value', models.CharField(blank=True, default='', max_length=120)),
                ('hours_line1_value_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line1_value_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line2_label', models.CharField(blank=True, default='', max_length=120)),
                ('hours_line2_label_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line2_label_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line2_value', models.CharField(blank=True, default='', max_length=120)),
                ('hours_line2_value_ar', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('hours_line2_value_en', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('copyright_suffix', models.CharField(blank=True, default='', help_text='e.g. | All Rights Reserved', max_length=255)),
                ('copyright_suffix_ar', models.CharField(blank=True, default='', help_text='e.g. | All Rights Reserved', max_length=255, null=True)),
                ('copyright_suffix_en', models.CharField(blank=True, default='', help_text='e.g. | All Rights Reserved', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Footer settings',
                'verbose_name_plural': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Footer link',
                'verbose_name_plural': 'Footer links',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
