# Generated by Django 6.0.1 on 2026-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footersettings_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Link title'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Link title'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Link title'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(help_text='e.g. /blog/ or https://…', max_length=500, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_main',
            field=models.CharField(blank=True, default='', help_text='Example: "About" in "About Us"', max_length=120, verbose_name='About — first part of title'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_main_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "About" in "About Us"', max_length=120, null=True, verbose_name='About — first part of title'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_main_en',
            field=models.CharField(blank=True, default='', help_text='Example: "About" in "About Us"', max_length=120, null=True, verbose_name='About — first part of title'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_span',
            field=models.CharField(blank=True, default='', help_text='Example: "Us" (appears in theme color)', max_length=120, verbose_name='About — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_span_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Us" (appears in theme color)', max_length=120, null=True, verbose_name='About — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_heading_span_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Us" (appears in theme color)', max_length=120, null=True, verbose_name='About — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='About — text'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_text_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About — text'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About — text'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Contact — address'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='address_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contact — address'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='address_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contact — address'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_main',
            field=models.CharField(blank=True, default='', help_text='Example: "Get In"', max_length=120, verbose_name='Get in touch — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_main_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Get In"', max_length=120, null=True, verbose_name='Get in touch — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_main_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Get In"', max_length=120, null=True, verbose_name='Get in touch — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_span',
            field=models.CharField(blank=True, default='', help_text='Example: "Touch"', max_length=120, verbose_name='Get in touch — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_span_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Touch"', max_length=120, null=True, verbose_name='Get in touch — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_heading_span_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Touch"', max_length=120, null=True, verbose_name='Get in touch — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact — email'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email_ar',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Contact — email'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email_en',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Contact — email'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='If empty, the main site logo is used.', null=True, upload_to='footer/', verbose_name='Footer logo'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_label',
            field=models.CharField(blank=True, default='', help_text='Example: "Monday - Friday"', max_length=120, verbose_name='Working hours — line 1 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_label_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Monday - Friday"', max_length=120, null=True, verbose_name='Working hours — line 1 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_label_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Monday - Friday"', max_length=120, null=True, verbose_name='Working hours — line 1 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_value',
            field=models.CharField(blank=True, default='', help_text='Example: "10:00 to 6:00"', max_length=120, verbose_name='Working hours — line 1 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_value_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "10:00 to 6:00"', max_length=120, null=True, verbose_name='Working hours — line 1 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line1_value_en',
            field=models.CharField(blank=True, default='', help_text='Example: "10:00 to 6:00"', max_length=120, null=True, verbose_name='Working hours — line 1 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Working hours — line 2 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_label_ar',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Working hours — line 2 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_label_en',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Working hours — line 2 label'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_value',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Working hours — line 2 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_value_ar',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Working hours — line 2 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='hours_line2_value_en',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Working hours — line 2 hours'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone_ar',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone_en',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_main',
            field=models.CharField(blank=True, default='', help_text='Example: "Recent" in "Recent Post"', max_length=120, verbose_name='Recent Post — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_main_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Recent" in "Recent Post"', max_length=120, null=True, verbose_name='Recent Post — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_main_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Recent" in "Recent Post"', max_length=120, null=True, verbose_name='Recent Post — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_span',
            field=models.CharField(blank=True, default='', help_text='Example: "Post"', max_length=120, verbose_name='Recent Post — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_span_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Post"', max_length=120, null=True, verbose_name='Recent Post — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='recent_heading_span_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Post"', max_length=120, null=True, verbose_name='Recent Post — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_main',
            field=models.CharField(blank=True, default='', help_text='Example: "Our" in "Our Solutions"', max_length=120, verbose_name='Our Solutions — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_main_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Our" in "Our Solutions"', max_length=120, null=True, verbose_name='Our Solutions — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_main_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Our" in "Our Solutions"', max_length=120, null=True, verbose_name='Our Solutions — first part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_span',
            field=models.CharField(blank=True, default='', help_text='Example: "Solutions"', max_length=120, verbose_name='Our Solutions — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_span_ar',
            field=models.CharField(blank=True, default='', help_text='Example: "Solutions"', max_length=120, null=True, verbose_name='Our Solutions — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='solutions_heading_span_en',
            field=models.CharField(blank=True, default='', help_text='Example: "Solutions"', max_length=120, null=True, verbose_name='Our Solutions — colored part'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='', verbose_name='X (Twitter) URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='YouTube URL'),
        ),
    ]
