# Generated by Django 6.0.1 on 2026-03-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footer_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Main text')),
                ('text_main_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Main text')),
                ('text_main_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Main text')),
                ('text_highlight', models.CharField(blank=True, default='', max_length=255, verbose_name='Highlighted text')),
                ('text_highlight_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Highlighted text')),
                ('text_highlight_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Highlighted text')),
                ('button_text', models.CharField(blank=True, default='', max_length=120, verbose_name='Button text')),
                ('button_text_ar', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Button text')),
                ('button_text_en', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, default='', help_text='Internal path like /contact/ or full URL.', max_length=500, verbose_name='Button URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Home CTA',
                'verbose_name_plural': 'Home CTA',
            },
        ),
    ]
