# Generated by Django 6.0.1 on 2026-03-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_home_cta_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dark_color',
            field=models.CharField(blank=True, help_text='Header (when fixed), footer, dark sections (e.g. #1d3338).', max_length=7, null=True, verbose_name='Dark brand background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='surface_color',
            field=models.CharField(blank=True, help_text='Main page background and light sections (e.g. #ececec).', max_length=7, null=True, verbose_name='Surface / page background'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Buttons, links, icons, progress bars, highlights — the color that should stand out.', max_length=7, null=True, verbose_name='Accent color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Gradients with accent, secondary buttons, subtle accents.', max_length=7, null=True, verbose_name='Secondary accent'),
        ),
    ]
