# Generated by Django 6.0.1 on 2026-03-25 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_body',
            field=models.TextField(blank=True, default='', verbose_name='"For you" block — text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_body_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='"For you" block — text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_body_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='"For you" block — text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_heading',
            field=models.CharField(blank=True, default='', help_text='e.g. "For you" / "من أجلكم".', max_length=255, verbose_name='"For you" block — title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_heading_ar',
            field=models.CharField(blank=True, default='', help_text='e.g. "For you" / "من أجلكم".', max_length=255, null=True, verbose_name='"For you" block — title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='for_you_heading_en',
            field=models.CharField(blank=True, default='', help_text='e.g. "For you" / "من أجلكم".', max_length=255, null=True, verbose_name='"For you" block — title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_background',
            field=models.ImageField(blank=True, help_text='Parallax background (optional).', null=True, upload_to='about_page/policy/', verbose_name='Policy section — background'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_overlay',
            field=models.PositiveSmallIntegerField(default=9, help_text='0–10, darker background behind text.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Policy section — overlay'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_main',
            field=models.CharField(blank=True, default='', help_text='Large heading above the carousel (e.g. commitment / quality).', max_length=255, verbose_name='Policy section — main title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_main_ar',
            field=models.CharField(blank=True, default='', help_text='Large heading above the carousel (e.g. commitment / quality).', max_length=255, null=True, verbose_name='Policy section — main title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_main_en',
            field=models.CharField(blank=True, default='', help_text='Large heading above the carousel (e.g. commitment / quality).', max_length=255, null=True, verbose_name='Policy section — main title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_span',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Policy section — highlighted title part'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_span_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Policy section — highlighted title part'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='policy_section_title_span_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Policy section — highlighted title part'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_heading',
            field=models.CharField(blank=True, default='', help_text='e.g. "Quality policy".', max_length=255, verbose_name='Quality policy — block title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_heading_ar',
            field=models.CharField(blank=True, default='', help_text='e.g. "Quality policy".', max_length=255, null=True, verbose_name='Quality policy — block title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_heading_en',
            field=models.CharField(blank=True, default='', help_text='e.g. "Quality policy".', max_length=255, null=True, verbose_name='Quality policy — block title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_points',
            field=models.TextField(blank=True, default='', help_text='One bullet per line.', verbose_name='Quality policy — bullet points'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_points_ar',
            field=models.TextField(blank=True, default='', help_text='One bullet per line.', null=True, verbose_name='Quality policy — bullet points'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_points_en',
            field=models.TextField(blank=True, default='', help_text='One bullet per line.', null=True, verbose_name='Quality policy — bullet points'),
        ),
    ]
