# Generated by Django 6.0.1 on 2026-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_page_policy_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_teaser',
            field=models.TextField(blank=True, default='', help_text='Optional short paragraph above the bullet list (teaser / lead-in).', verbose_name='Quality policy — intro before bullets'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_teaser_ar',
            field=models.TextField(blank=True, default='', help_text='Optional short paragraph above the bullet list (teaser / lead-in).', null=True, verbose_name='Quality policy — intro before bullets'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='quality_policy_teaser_en',
            field=models.TextField(blank=True, default='', help_text='Optional short paragraph above the bullet list (teaser / lead-in).', null=True, verbose_name='Quality policy — intro before bullets'),
        ),
    ]
