# Generated by Django 6.0.1 on 2026-03-26 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_quality_policy_teaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, help_text='Background for the page title (parallax).', null=True, upload_to='contact_page/hero/', verbose_name='Hero background image')),
                ('hero_overlay', models.PositiveSmallIntegerField(default=7, help_text='0 = light, 10 = very dark (theme data-overlay).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Hero overlay darkness')),
                ('hero_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — first part')),
                ('hero_title_main_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — first part')),
                ('hero_title_main_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — first part')),
                ('hero_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — highlighted part')),
                ('hero_title_span_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — highlighted part')),
                ('hero_title_span_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — highlighted part')),
                ('hero_breadcrumb_parent_label', models.CharField(blank=True, default='', help_text='e.g. "Contact" — appears between Home and current page title.', max_length=120, verbose_name='Breadcrumb middle label')),
                ('hero_breadcrumb_parent_label_ar', models.CharField(blank=True, default='', help_text='e.g. "Contact" — appears between Home and current page title.', max_length=120, null=True, verbose_name='Breadcrumb middle label')),
                ('hero_breadcrumb_parent_label_en', models.CharField(blank=True, default='', help_text='e.g. "Contact" — appears between Home and current page title.', max_length=120, null=True, verbose_name='Breadcrumb middle label')),
                ('sidebar_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Sidebar title — first part')),
                ('sidebar_title_main_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sidebar title — first part')),
                ('sidebar_title_main_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sidebar title — first part')),
                ('sidebar_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Sidebar title — highlighted part')),
                ('sidebar_title_span_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sidebar title — highlighted part')),
                ('sidebar_title_span_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sidebar title — highlighted part')),
                ('sidebar_intro', models.TextField(blank=True, default='', help_text='Short paragraph next to contact details.', verbose_name='Sidebar intro text')),
                ('sidebar_intro_ar', models.TextField(blank=True, default='', help_text='Short paragraph next to contact details.', null=True, verbose_name='Sidebar intro text')),
                ('sidebar_intro_en', models.TextField(blank=True, default='', help_text='Short paragraph next to contact details.', null=True, verbose_name='Sidebar intro text')),
                ('form_heading_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Form heading — first part')),
                ('form_heading_main_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Form heading — first part')),
                ('form_heading_main_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Form heading — first part')),
                ('form_heading_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Form heading — highlighted part')),
                ('form_heading_span_ar', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Form heading — highlighted part')),
                ('form_heading_span_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Form heading — highlighted part')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contact page',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_ar',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Paste the full iframe src URL from Google Maps (Share → Embed a map).', null=True, verbose_name='Google Maps embed URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only with country code, no spaces (e.g. 966501234567). Used for chat links.', max_length=32, null=True, verbose_name='WhatsApp number'),
        ),
    ]
