# Generated by Django 6.0.1 on 2026-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_page_and_site_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Paste the iframe src URL from Google Maps (Share → Embed a map). If empty, the contact page uses the default map from settings (e.g. Jeddah).', null=True, verbose_name='Google Maps embed URL'),
        ),
    ]
