# Generated by Django 6.0.1 on 2026-04-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Country code + number, digits only (e.g. 966501234567). Opens WhatsApp chat directly (wa.me).', max_length=32, verbose_name='WhatsApp number'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Shown in the footer. Tap opens the dialer (tel:). You can use spaces or + for display; digits are used for the actual call link.', max_length=80, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone_ar',
            field=models.CharField(blank=True, default='', help_text='Shown in the footer. Tap opens the dialer (tel:). You can use spaces or + for display; digits are used for the actual call link.', max_length=80, null=True, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone_en',
            field=models.CharField(blank=True, default='', help_text='Shown in the footer. Tap opens the dialer (tel:). You can use spaces or + for display; digits are used for the actual call link.', max_length=80, null=True, verbose_name='Contact — phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='', verbose_name='X URL'),
        ),
    ]
