# Generated by Django 6.0.1 on 2026-04-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_footer_whatsapp_and_phone_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='phone_call_number',
            field=models.CharField(blank=True, default='', help_text='Example: +201234567890', max_length=20, verbose_name='Direct call number'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp number'),
        ),
    ]
