# Generated by Django 6.0.1 on 2026-04-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_footersettings_phone_call_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='phone_call_number',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='whatsapp_number',
        ),
    ]
