# Generated by Django 6.0.1 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_footersettings_phone_call_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_video_caption",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Home hero video caption"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_video_caption_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_video_caption_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

