# Generated by Django 6.0.1 on 2026-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_hero_video_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecta',
            name='button_text',
            field=models.CharField(blank=True, default='', help_text='Label shown on the call-to-action button.', max_length=120, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='button_text_ar',
            field=models.CharField(blank=True, default='', help_text='Label shown on the call-to-action button.', max_length=120, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='button_text_en',
            field=models.CharField(blank=True, default='', help_text='Label shown on the call-to-action button.', max_length=120, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='button_url',
            field=models.CharField(blank=True, default='', help_text='Internal path like /contact/ or a full https:// URL.', max_length=500, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When unchecked, this block is hidden on the home page.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_highlight',
            field=models.CharField(blank=True, default='', help_text='Optional second line or accent phrase (theme color). Leave empty if not used.', max_length=255, verbose_name='Highlighted text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_highlight_ar',
            field=models.CharField(blank=True, default='', help_text='Optional second line or accent phrase (theme color). Leave empty if not used.', max_length=255, null=True, verbose_name='Highlighted text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_highlight_en',
            field=models.CharField(blank=True, default='', help_text='Optional second line or accent phrase (theme color). Leave empty if not used.', max_length=255, null=True, verbose_name='Highlighted text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_main',
            field=models.CharField(blank=True, default='', help_text='Primary headline line on the home hero.', max_length=255, verbose_name='Main text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_main_ar',
            field=models.CharField(blank=True, default='', help_text='Primary headline line on the home hero.', max_length=255, null=True, verbose_name='Main text'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='text_main_en',
            field=models.CharField(blank=True, default='', help_text='Primary headline line on the home hero.', max_length=255, null=True, verbose_name='Main text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_caption',
            field=models.CharField(blank=True, help_text='Short phrase displayed over the hero background video (bottom-right).', max_length=255, null=True, verbose_name='Home hero video caption'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_caption_ar',
            field=models.CharField(blank=True, help_text='Short phrase displayed over the hero background video (bottom-right).', max_length=255, null=True, verbose_name='Home hero video caption'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_caption_en',
            field=models.CharField(blank=True, help_text='Short phrase displayed over the hero background video (bottom-right).', max_length=255, null=True, verbose_name='Home hero video caption'),
        ),
    ]
