# Generated by Django 6.0.1 on 2026-03-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_page_and_site_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='send_via',
            field=models.CharField(choices=[('email', 'Company email'), ('whatsapp', 'Company WhatsApp')], default='email', max_length=16, verbose_name='Send via'),
        ),
    ]
