# Generated by Django 6.0.1 on 2026-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_send_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='send_via',
            field=models.CharField(choices=[('email', 'Company email'), ('whatsapp', 'Company WhatsApp'), ('both', 'Email and WhatsApp')], default='email', max_length=16, verbose_name='Send via'),
        ),
    ]
