# Generated by Django 6.0.1 on 2026-04-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmessage_send_via'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
    ]
