# Generated by Django 6.0.1 on 2026-03-29 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, help_text='Background for the page title (parallax).', null=True, upload_to='service_page/hero/', verbose_name='Hero background image')),
                ('hero_overlay', models.PositiveSmallIntegerField(default=7, help_text='0 = light, 10 = very dark (theme data-overlay).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Hero overlay darkness')),
                ('hero_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — first part')),
                ('hero_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — highlighted part')),
                ('hero_breadcrumb_parent_label', models.CharField(blank=True, default='', help_text='e.g. "Pages" — appears between Home and current page.', max_length=120, verbose_name='Breadcrumb middle label')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='about_page/gallery/', verbose_name='Gallery image 1')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='about_page/gallery/', verbose_name='Gallery image 2')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='about_page/gallery/', verbose_name='Gallery image 3')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='about_page/gallery/', verbose_name='Gallery image 4')),
                ('intro_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Intro title — first part')),
                ('intro_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Intro title — highlighted part')),
                ('intro_lead', models.TextField(blank=True, default='', verbose_name='Intro lead paragraph')),
                ('intro_body', models.TextField(blank=True, default='', verbose_name='Intro body text')),
                ('intro_read_more_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Read more button label')),
                ('intro_read_more_url', models.CharField(blank=True, default='', help_text='e.g. /contact/ or full URL; leave empty to hide button.', max_length=500, verbose_name='Read more URL')),
                ('tab_mission_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Tab: Mission label')),
                ('tab_vision_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Tab: Vision label')),
                ('tab_values_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Tab: Values label')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about_page/tabs/', verbose_name='Mission — image')),
                ('mission_heading_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Mission — heading first part')),
                ('mission_heading_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Mission — heading highlight')),
                ('mission_lead', models.TextField(blank=True, default='', verbose_name='Mission — lead')),
                ('mission_body', models.TextField(blank=True, default='', verbose_name='Mission — body')),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about_page/tabs/', verbose_name='Vision — image')),
                ('vision_heading_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Vision — heading first part')),
                ('vision_heading_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Vision — heading highlight')),
                ('vision_lead', models.TextField(blank=True, default='', verbose_name='Vision — lead')),
                ('vision_body', models.TextField(blank=True, default='', verbose_name='Vision — body')),
                ('values_image', models.ImageField(blank=True, null=True, upload_to='about_page/tabs/', verbose_name='Values — image')),
                ('values_heading_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Values — heading first part')),
                ('values_heading_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Values — heading highlight')),
                ('values_lead', models.TextField(blank=True, default='', verbose_name='Values — lead')),
                ('values_body', models.TextField(blank=True, default='', verbose_name='Values — body')),
                ('policy_section_background', models.ImageField(blank=True, help_text='Parallax background (optional).', null=True, upload_to='about_page/policy/', verbose_name='Policy section — background')),
                ('policy_section_overlay', models.PositiveSmallIntegerField(default=9, help_text='0–10, darker background behind text.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Policy section — overlay')),
                ('policy_section_title_main', models.CharField(blank=True, default='', help_text='Large heading above the carousel (e.g. commitment / quality).', max_length=255, verbose_name='Policy section — main title')),
                ('policy_section_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Policy section — highlighted title part')),
                ('quality_policy_heading', models.CharField(blank=True, default='', help_text='e.g. "Quality policy".', max_length=255, verbose_name='Quality policy — block title')),
                ('quality_policy_teaser', models.TextField(blank=True, default='', help_text='Optional short paragraph above the bullet list (teaser / lead-in).', verbose_name='Quality policy — intro before bullets')),
                ('quality_policy_points', models.TextField(blank=True, default='', help_text='One bullet per line.', verbose_name='Quality policy — bullet points')),
                ('for_you_heading', models.CharField(blank=True, default='', help_text='e.g. "For you" / "من أجلكم".', max_length=255, verbose_name='"For you" block — title')),
                ('for_you_body', models.TextField(blank=True, default='', verbose_name='"For you" block — text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
    ]
