# Generated by Django 6.0.1 on 2026-04-02 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='services/landing/hero/', verbose_name='Hero background image')),
                ('hero_overlay', models.PositiveSmallIntegerField(default=7, help_text='1–10 (parallax overlay strength).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hero overlay darkness')),
                ('hero_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — main')),
                ('hero_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Hero title — highlight')),
                ('breadcrumb_parent_label', models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, verbose_name='Breadcrumb — middle link label')),
                ('breadcrumb_current_label', models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, verbose_name='Breadcrumb — current page label')),
                ('sidebar_title_main', models.CharField(blank=True, default='', max_length=255, verbose_name='Features block — title (main)')),
                ('sidebar_title_span', models.CharField(blank=True, default='', max_length=255, verbose_name='Features block — title (highlight)')),
                ('sidebar_intro', models.TextField(blank=True, default='', verbose_name='Features block — intro under title')),
                ('section_pattern_image', models.ImageField(blank=True, help_text='Optional tile/pattern; leave empty to use theme default.', null=True, upload_to='services/landing/pattern/', verbose_name='Grey section — pattern background (optional)')),
            ],
            options={
                'verbose_name': 'Our services page',
                'verbose_name_plural': 'Our services page',
            },
        ),
        migrations.CreateModel(
            name='ServicesFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('icon_class', models.CharField(default='flaticon-innovation', help_text='Example: flaticon-innovation or "fas fa-cog". No angle brackets.', max_length=120, verbose_name='Icon CSS classes')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_promoted', models.BooleanField(default=False, help_text='At most one promoted item is shown next to the intro; others appear in the grid below.', verbose_name='Show beside sidebar (large cell)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.serviceslanding', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Service feature item',
                'verbose_name_plural': 'Service feature items',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
