# Generated by Django 6.0.1 on 2026-04-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_landing_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfeature',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='servicesfeature',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='servicesfeature',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='servicesfeature',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='breadcrumb_current_label_ar',
            field=models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, null=True, verbose_name='Breadcrumb — current page label'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='breadcrumb_current_label_en',
            field=models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, null=True, verbose_name='Breadcrumb — current page label'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='breadcrumb_parent_label_ar',
            field=models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, null=True, verbose_name='Breadcrumb — middle link label'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='breadcrumb_parent_label_en',
            field=models.CharField(blank=True, default='', help_text='Leave blank for default translation.', max_length=120, null=True, verbose_name='Breadcrumb — middle link label'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='hero_title_main_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — main'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='hero_title_main_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — main'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='hero_title_span_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — highlight'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='hero_title_span_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hero title — highlight'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_intro_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Features block — intro under title'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_intro_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Features block — intro under title'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_title_main_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Features block — title (main)'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_title_main_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Features block — title (main)'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_title_span_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Features block — title (highlight)'),
        ),
        migrations.AddField(
            model_name='serviceslanding',
            name='sidebar_title_span_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Features block — title (highlight)'),
        ),
    ]
