# Generated by Django 6.0.1 on 2026-04-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_landing_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Services extended page', 'verbose_name_plural': 'Services extended page'},
        ),
    ]
