# Generated by Django 6.0.1 on 2026-04-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcategory_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'News article', 'verbose_name_plural': 'News articles'},
        ),
    ]
