"""
Django settings for core_cms project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mt9cnee45nd^cvnc(&s3os7-=!dq2ac_ya+^*lw17gkkd#3&qa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold', # [ENAS CUSTOM] 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',  # قبل التطبيقات اللي فيها ترجمة

    # [ENAS CUSTOM] 
    'blog',
    'contact',
    'pages',
    "projects.apps.ProjectsConfig",
    'services',
    'core',

    # extra apps
    'ckeditor',             # دا لعرض CKEditor
    'ckeditor_uploader',    # لو هترفعي صور
    'sass_processor',
]

# CKEditor Config
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'core.middleware.AdminSiteLanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # [ENAS CUSTOM] 
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True

# Used as From: when sending contact form emails (set real SMTP in production).
DEFAULT_FROM_EMAIL = "webmaster@localhost"

# عنوان المتصفح عندما يكون اسم الموقع في الأدمن فاضياً (لا يظهر IP/المضيف كعنوان).
SITE_TITLE_FALLBACK = "بيوتات التميز"

# خريطة صفحة الاتصال عندما يكون حقل «Google Maps embed URL» في إعدادات الموقع فاضياً (جدة، السعودية).
DEFAULT_MAP_EMBED_URL = (
    "https://maps.google.com/maps?q=Jeddah%2C+Saudi+Arabia&z=11&hl=ar&ie=UTF8&output=embed"
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # BASE_DIR / 'administration/static',  # أضف أي مسارات ثابتة أخرى إذا كانت موجودة
]

SASS_PROCESSOR_ROOT = BASE_DIR / 'static'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

# Media files (uploaded via ImageField/FileField)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LANGUAGES = [
    ('ar', _('Arabic')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Modeltranslation settings
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ar'
MODELTRANSLATION_LANGUAGES = ('ar', 'en')
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'ar'


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL: str = 'accounts.CustomUser'

# LOGOUT_REDIRECT_URL = '/'
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = "/"


def unfold_admin_rtl_stylesheet(request):
    """Extra admin CSS: RTL alignment for Unfold dashboard model tables."""
    from django.templatetags.static import static

    return static("admin/css/unfold-rtl-overrides.css")


def unfold_admin_branding_stylesheet(request):
    """شعار أوضح + خط أكبر في الأدمن."""
    from django.templatetags.static import static

    return static("admin/css/unfold-admin-branding.css")


from core.unfold_branding import unfold_admin_favicon_url, unfold_admin_logo_url

UNFOLD = {
    "SITE_TITLE": _("Byotat Al Tamayoz"),
    "SITE_HEADER": _("Byotat Al Tamayoz"),
    "SITE_SUBHEADER": _("Welcome to Dashboard"),
    "SHOW_LANGUAGES": True,
    # بدون THEME ثابت — يظهر مبدّل فاتح / داكن / النظام في قائمة المستخدم بالسايدبار
    "SITE_LOGO": {
        "light": unfold_admin_logo_url,
        "dark": unfold_admin_logo_url,
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "href": unfold_admin_favicon_url,
        },
    ],
    "STYLES": [
        unfold_admin_rtl_stylesheet,
        unfold_admin_branding_stylesheet,
    ],
}




JAZZMIN_SETTINGS = {
    "site_title": "لوحة التحكم",
    "site_header": "إدارة الموقع",
    "site_brand": "Admin",

    "welcome_sign": "أهلاً بيكي 👋",

    "show_ui_builder": True,

    # التحكم في السايدبار
    "show_sidebar": True,   # خليها False لو عايزة تخفيه بالكامل

    # ترتيب المودلز
    "order_with_respect_to": ["auth", "your_app"],

    # تغيير اللغة
    "language_chooser": True,

    # أيقونات
    "icons": {
        "auth.user": "fas fa-user",
    },
    
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"